# Generated by Django 4.1.5 on 2023-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='미션상태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(max_length=20, verbose_name='티어'),
        ),
    ]
