# Generated by Django 4.1.5 on 2023-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapps_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='UserBank',
        ),
        migrations.RenameModel(
            old_name='Invite',
            new_name='UserInvite',
        ),
        migrations.AddField(
            model_name='user',
            name='e_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
