# Generated by Django 4.1.5 on 2023-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='미션 이름')),
                ('point', models.CharField(max_length=128, verbose_name='포인트')),
                ('description', models.CharField(max_length=128, verbose_name='설명')),
            ],
            options={
                'verbose_name': '미션',
                'verbose_name_plural': '미션',
                'db_table': 'shinhan_mission',
            },
        ),
    ]
